// All doxygen comments were generated by AI, model: gpt-5.

/**
 * @file shared.h
 * @brief Common definitions shared between client and server.
 *
 * Contains network packet structures, game constants, and data types
 * used for client-server communication over ENet.
 */
#pragma once

#include <stdint.h>
#include <stdbool.h>

/** @name Game Constants
 *  @{
 */
#define WORLD_SIZE 6000   /**< Diameter of the circular game world */
#define PORT 7777         /**< Default server port */
#define MAX_CLIENTS 64    /**< Maximum concurrent players (including bots) */
#define MAX_FOOD 2000     /**< Maximum food items in the world */
#define MAX_TRAIL 120     /**< Maximum trail segments per snake */
/** @} */

/**
 * @brief Packet type identifiers for network communication.
 */
enum PacketType
{
    JOIN_PACKET = 1,  /**< Client requests to join the game */
    INIT_PACKET,      /**< Server confirms join with player ID */
    INPUT_PACKET,     /**< Client sends input (angle, boost) */
    WORLD_PACKET,     /**< Server broadcasts world state */
    DIE_PACKET        /**< Server notifies client of death */
};

#pragma pack(push, 1)

/**
 * @brief RGB color with 8-bit channels.
 */
typedef struct
{
    uint8_t r;  /**< Red component (0-255) */
    uint8_t g;  /**< Green component (0-255) */
    uint8_t b;  /**< Blue component (0-255) */
} ColorRGB;

/**
 * @brief Network-serialized food item.
 */
typedef struct
{
    uint16_t id;    /**< Unique food identifier */
    int16_t x, y;   /**< World position */
    uint8_t val;    /**< Nutritional value (affects size and score) */
    uint8_t r, g, b; /**< RGB color */
} NetFood;

/**
 * @brief Network-serialized snake state.
 *
 * Contains all data needed to render a snake on the client,
 * including position, trail, appearance, and game state.
 */
typedef struct
{
    uint16_t id;         /**< Player/bot slot ID */
    int16_t x, y;        /**< Head position in world coordinates */
    int16_t angle;       /**< Movement direction in degrees */
    uint16_t score;      /**< Current score (affects size) */
    uint8_t dead;        /**< Death flag (0 = alive) */
    uint16_t immunity;   /**< Remaining immunity ticks after spawn */
    uint8_t r, g, b;     /**< Snake body color */
    char name[16];       /**< Player display name */
    uint8_t trail_len;   /**< Number of active trail segments */
    int16_t trail_x[MAX_TRAIL];  /**< Trail segment X coordinates */
    int16_t trail_y[MAX_TRAIL];  /**< Trail segment Y coordinates */
} NetSnake;

/**
 * @brief Packet sent by client to join the game.
 */
typedef struct
{
    uint8_t type;    /**< Must be JOIN_PACKET */
    char name[16];   /**< Requested player name */
} JoinPacket;

/**
 * @brief Packet sent by server to confirm player join.
 */
typedef struct
{
    uint8_t type;          /**< Must be INIT_PACKET */
    uint16_t player_id;    /**< Assigned player slot ID */
    uint16_t world_width;  /**< World diameter for client setup */
} InitPacket;

/**
 * @brief Packet sent by client with player input.
 *
 * Sent at high frequency (every frame) to update player direction.
 */
typedef struct
{
    uint8_t type;   /**< Must be INPUT_PACKET */
    float angle;    /**< Target movement angle in radians */
    uint8_t boost;  /**< Boost flag (1 = boosting) */
} InputPacket;

/**
 * @brief Packet sent by server when player dies.
 */
typedef struct
{
    uint8_t type;          /**< Must be DIE_PACKET */
    uint32_t final_score;  /**< Player's score at death */
} DiePacket;

/**
 * @brief Header for world state packet.
 *
 * Followed by snake_count NetSnake structs, then food_count NetFood structs.
 * Sequence number prevents older packets from overwriting newer state.
 */
typedef struct
{
    uint8_t type;          /**< Must be WORLD_PACKET */
    uint32_t sequence;     /**< Incrementing packet sequence for ordering */
    uint16_t snake_count;  /**< Number of NetSnake entries following */
    uint16_t food_count;   /**< Number of NetFood entries following */
} WorldPacket;

#pragma pack(pop)
